#!/bin/bash
touch .env
echo "POSTGRES_USER=$POSTGRES_USERNAME" > .env
echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
echo "POSTGRES_DB=$POSTGRES_DB" >> .env
echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env
echo "POSTGRES_PORT=$POSTGRES_PORT" >> .env
echo "HOME=$HOME" >> .env
echo "NEXT_PORT=$NEXT_PORT" >> .env
echo "SERVER_PORT=$SERVER_PORT" >> .env
echo "AUTH0_SECRET=$AUTH0_SECRET" >> .env
echo "AUTH0_BASE_URL=$AUTH0_BASE_URL" >> .env
echo "AUTH0_ISSUER_BASE_URL=$AUTH0_ISSUER_BASE_URL" >> .env
echo "AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID" >> .env
echo "AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET" >> .env
echo "LOCAL_DATABASE_URL=$LOCAL_DATABASE_URL" >> .env
echo "REMOTE_DATABASE_URL=$REMOTE_DATABASE_URL" >> .env
